export const LOAD_ITEMS = "LOAD_ITEMS";

export const ADD_TO_FAVOURITES = "ADD_TO_FAVOURITES";

export const REMOVE_FROM_FAVOURITES = "REMOVE_FROM_FAVOURITES";

export const ADD_TO_CART = "ADD_TO_CART";

export const REMOVE_FROM_CART = "REMOVE_FROM_CART";